server:
  port: 6001
  servlet:
    context-path: /open
spring:
  profiles:
    active: dev
  application:
    name: indi-open-api
  cloud:
    nacos:
      discovery:
        server-addr: http://nacos.goyoto.cn
        namespace: 065b143e-0067-4bb0-aeb2-aefac322829f
      config:
        server-addr: http://nacos.goyoto.cn
        file-extension: yml
        namespace: 065b143e-0067-4bb0-aeb2-aefac322829f


