logging.level.root=debug
logging.file.path=logs
logging.level.org.springframework=ERROR
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.apache.catalina=ERROR
logging.level.org.apache.tomcat=ERROR
logging.level.org.apache.coyote=ERROR
logging.level.org.hibernate=ERROR
logging.level.io.netty=ERROR
logging.level.springfox=ERROR
logging.level.Validator=ERROR
logging.level.javax.activation=ERROR
logging.level.jdk.event.security=ERROR